import React, { ReactNode } from 'react'
import Head from 'next/head'
import { NavBar } from '../navBar'
import { Footer } from '../footer'

interface IProps {
  children: ReactNode
}

const MainLayout = (props: IProps) => {
  const { children } = props
  return (
    <div>
         <>
      <Head>
        <title>Musical mix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main>
        { children }
      </main>
       <Footer />
    </>
      
    </div>
  )
}

export default MainLayout
